Patch out the import of serial, which causes a traceback on initialization of
cloudbase-init.  Either we import pyserial or some form of restructuring should
happen upstream as few platforms seem likely to find logging to serial to be
useful.

--- ORIGINAL/log.py	2016-01-25 16:11:17.453264452 -0800
+++ cloudbase-init-0.9.9/cloudbaseinit/utils/log.py	2016-01-25 16:11:31.787933714 -0800
@@ -13,7 +13,6 @@
 #    under the License.
 
 import logging
-import serial
 import six
 
 from oslo_config import cfg
