[?1034h---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)

     61         reload(sys.modules[modname])
     62     else:
---> 63         __import__(modname)
     64         
     65 

ImportError: No module named ipy_user_conf
WARNING: Loading of ipy_user_conf failed.

[?1034h---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)

     61         reload(sys.modules[modname])
     62     else:
---> 63         __import__(modname)
     64         
     65 

ImportError: No module named ipy_user_conf
WARNING: Loading of ipy_user_conf failed.

Test making a FakeModule object with initial data ... ok
Testcase $HOME is not set, os=='poix'. ... ok
test_get_ipython_dir_1, Testcase to see if we can call get_ipython_dir without Exceptions. ... ok
test_get_ipython_dir_2, Testcase to see if we can call get_ipython_dir without Exceptions. ... ok
test_get_ipython_dir_3, Testcase to see if we can call get_ipython_dir without Exceptions. ... ok
Testcase to see if we can call get_security_dir without Exceptions. ... ERROR
Testcase to see if we can call get_log_dir without Exceptions. ... ERROR
test_popkey_1, Basic usage test of popkey ... ok
test_popkey_2, Test to see that popkey of non occuring keys ... ok
test_popkey_3, Tests to see that popkey calls returns the correct value ... ok
Various tests for filefind ... ok
reset must clear most namespaces. ... ok
Check that %run doesn't damage __builtins__ ... ok
Check that the type of __builtins__ doesn't change with %run. ... ok
Test that prompts correctly generate after %run ... ok
IPython.tests.test_magic.test_rehashx(True,) ... ok
IPython.tests.test_magic.test_rehashx(True,) ... ok
Test that object's __del__ methods are called on exit. ... WARNING: Configuration file ipythonrc not found. Ignoring request.
------------------------------------------------------------
Traceback (most recent call last):
    fname = filefind(fname,incpath)
    ' not found in current or supplied directories:' + `alt_dirs`

WARNING: Problems loading configuration file 'ipythonrc'
Starting with default -bare bones- configuration.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)

     61         reload(sys.modules[modname])
     62     else:
---> 63         __import__(modname)
     64         
     65 

ImportError: No module named ipy_user_conf
WARNING: Loading of ipy_user_conf failed.

FAIL
IPython.tests.test_magic.test_shist([(1, 'hello'), (2, 'world'), (3, 'karhu')], [(1, 'hello'), (2, 'world'), (3, 'karhu')]) ... ok
IPython.tests.test_magic.test_shist('world', 'world') ... ok
IPython.tests.test_magic.test_numpy_clear_array_undec(True,) ... ok
IPython.tests.test_magic.test_numpy_clear_array_undec(False,) ... ok
Failure: SkipTest (Skipping test: test_fail_dec. Test skipped due to test condition.) ... SKIP: Skipping test: test_fail_dec. Test skipped due to test condition.
Failure: SkipTest (Skipping test: test_fail_dec2. This one shouldn not run) ... SKIP: Skipping test: test_fail_dec2. This one shouldn not run
Failure: SkipTest (Skipping test: test_fail_dec3. This test is known to fail) ... SKIP: Skipping test: test_fail_dec3. This test is known to fail
IPython.tests.test_magic.test_paste(1, 1) ... ok
IPython.tests.test_magic.test_paste(2, 2) ... ok
IPython.tests.test_magic.test_paste([1, 2, 3], [1, 2, 3]) ... ok
IPython.tests.test_magic.test_paste([1, 4, 9], [1, 4, 9]) ... ok
Doctest: IPython.tests.test_magic.doctest_hist_f ... ok
Doctest: IPython.tests.test_magic.doctest_hist_r ... ok
Doctest: IPython.tests.test_magic.doctest_refbug ... ok
Doctest: IPython.tests.test_magic.doctest_run_builtins ... ok
Doctest: IPython.tests.test_magic.doctest_run_ns ... ok
Doctest: IPython.tests.test_magic.doctest_run_ns2 ... ok
Make sure we find sys.exectable for python. ... ok
Try to find pythonw on Windows. ... SKIP: Skipping test: test_find_cmd. This test only runs under Windows
Make sure that FindCmdError is raised if we can't find the cmd. ... FAIL
IPython.tests.test_platutils.test_get_long_path_name_win32 ... SKIP: Skipping test: test_get_long_path_name_win32. This test only runs under Windows
IPython.tests.test_platutils.test_get_long_path_name ... ok

======================================================================
ERROR: Testcase to see if we can call get_security_dir without Exceptions.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/vendor-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
    sdir = genutils.get_security_dir()
    os.mkdir(security_dir, 0700)

======================================================================
ERROR: Testcase to see if we can call get_log_dir without Exceptions.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/vendor-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
    sdir = genutils.get_log_dir()
    os.mkdir(log_dir, 0777)

======================================================================
FAIL: Test that object's __del__ methods are called on exit.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/vendor-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
    nt.assert_equals(out,'obj_del.py: object A deleted')
AssertionError: '\x1b[?1034hobj_del.py: object A deleted' != 'obj_del.py: object A deleted'
-------------------- >> begin captured stdout << ---------------------

--------------------- >> end captured stdout << ----------------------
    "'\\x1b[?1034hobj_del.py: object A deleted' != 'obj_del.py: object A deleted'" = '%s != %s' % (safe_repr('\x1b[?1034hobj_del.py: object A deleted'), safe_repr('obj_del.py: object A deleted'))
    "'\\x1b[?1034hobj_del.py: object A deleted' != 'obj_del.py: object A deleted'" = self._formatMessage("'\\x1b[?1034hobj_del.py: object A deleted' != 'obj_del.py: object A deleted'", "'\\x1b[?1034hobj_del.py: object A deleted' != 'obj_del.py: object A deleted'")
>>  raise self.failureException("'\\x1b[?1034hobj_del.py: object A deleted' != 'obj_del.py: object A deleted'")
    

======================================================================
FAIL: Make sure that FindCmdError is raised if we can't find the cmd.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/vendor-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
    nt.assert_raises(FindCmdError,find_cmd,'asdfasdf')
AssertionError: FindCmdError not raised


----------------------------------------------------------------------
Ran 52 tests 

FAILED (SKIP=10, errors=2, failures=2)
>print(type(__builtins__))
>print(type(__builtins__))
obj_del.py: object A deleted
[?1034h---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)

     61         reload(sys.modules[modname])
     62     else:
---> 63         __import__(modname)
     64         
     65 

ImportError: No module named ipy_user_conf
WARNING: Loading of ipy_user_conf failed.

Check that is_complete works. ... ok
Tests line completion heuristic. ... ok
Tests line completion heuristic. ... ok
Tests line completion heuristic. ... ok
IPython.frontend.tests.test_prefilterfrontend.test_capture ... ok
IPython.frontend.tests.test_prefilterfrontend.test_completion_equal ... ---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)

     61         reload(sys.modules[modname])
     62     else:
---> 63         __import__(modname)
     64         
     65 

ImportError: No module named ipy_user_conf
WARNING: Loading of ipy_user_conf failed.

ok
IPython.frontend.tests.test_prefilterfrontend.test_completion_indexing ... ---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)

     61         reload(sys.modules[modname])
     62     else:
---> 63         __import__(modname)
     64         
     65 

ImportError: No module named ipy_user_conf
WARNING: Loading of ipy_user_conf failed.

ok
IPython.frontend.tests.test_prefilterfrontend.test_completion_parenthesis ... ok
IPython.frontend.tests.test_prefilterfrontend.test_completion_simple ... ok
IPython.frontend.tests.test_prefilterfrontend.test_execution ... ---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)

     61         reload(sys.modules[modname])
     62     else:
---> 63         __import__(modname)
     64         
     65 

ImportError: No module named ipy_user_conf
WARNING: Loading of ipy_user_conf failed.

ok
IPython.frontend.tests.test_prefilterfrontend.test_help ... ---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)

     61         reload(sys.modules[modname])
     62     else:
---> 63         __import__(modname)
     64         
     65 

ImportError: No module named ipy_user_conf
WARNING: Loading of ipy_user_conf failed.

ok
IPython.frontend.tests.test_prefilterfrontend.test_magic ... ---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)

     61         reload(sys.modules[modname])
     62     else:
---> 63         __import__(modname)
     64         
     65 

ImportError: No module named ipy_user_conf
WARNING: Loading of ipy_user_conf failed.

ok
IPython.frontend.tests.test_prefilterfrontend.test_multiline ... ok
A simple test to see if we can execute a process and get the output. ... ok
Checks that we can send characters on stdin to the process. ... ok
Check that we can kill a process, and its subprocess. ... ok

----------------------------------------------------------------------
Ran 16 tests 

OK
[?1034h---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)

     61         reload(sys.modules[modname])
     62     else:
---> 63         __import__(modname)
     64         
     65 

ImportError: No module named ipy_user_conf
WARNING: Loading of ipy_user_conf failed.

Doctest: IPython.tools.utils.extractVars ... ok
Doctest: IPython.tools.utils.list_strings ... ok
Doctest: IPython.tools.utils.marquee ... ok
Doctest: IPython.tools.utils.shexp ... ok
Doctest: test_tools_utils.txt ... ok

----------------------------------------------------------------------
Ran 5 tests 

OK
[?1034h---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)

     61         reload(sys.modules[modname])
     62     else:
---> 63         __import__(modname)
     64         
     65 

ImportError: No module named ipy_user_conf
WARNING: Loading of ipy_user_conf failed.

Doctest: IPython.testing.decorator_msim.decorator ... ok
Doctest: IPython.testing.decorator_msim.getinfo ... ok
Doctest: IPython.testing.decorators ... ok
Doctest: IPython.testing.decorators.make_label_dec ... ok
Doctest: IPython.testing.plugin.dtexample.iprand ... ok
Doctest: IPython.testing.plugin.dtexample.iprand_all ... ok
Doctest: IPython.testing.plugin.dtexample.pyfunc ... ok
Doctest: IPython.testing.plugin.dtexample.random_all ... ok
Doctest: IPython.testing.plugin.dtexample.ranfunc ... ok
Doctest: IPython.testing.plugin.simple.ipyfunc2 ... ok
Doctest: IPython.testing.plugin.simple.pyfunc ... ok
Doctest: IPython.testing.plugin.test_ipdoctest.doctest_multiline1 ... ok
Doctest: IPython.testing.plugin.test_ipdoctest.doctest_multiline2 ... ok
Doctest: IPython.testing.plugin.test_ipdoctest.doctest_multiline3 ... ok
Doctest: IPython.testing.plugin.test_ipdoctest.doctest_run_builtins ... ok
Doctest: IPython.testing.plugin.test_ipdoctest.doctest_simple ... ok
A trivial passing test. ... ok
Doctest: IPython.testing.plugin.test_refs.doctest_ivars ... ok
Doctest: IPython.testing.plugin.test_refs.doctest_refs ... ok
Doctest: IPython.testing.plugin.test_refs.doctest_run ... ok
Doctest: IPython.testing.plugin.test_refs.doctest_runvars ... ok
Another deliberately broken test - we want to skip this one. ... SKIP: Skipping test: test_deliberately_broken2. Testing the skip decorator
Doctest-skipping decorator should preserve the docstring. ... ok
Doctest-skipping decorator should preserve function signature. ... ok
IPython.testing.tests.test_decorators.test_linux ... ok
IPython.testing.tests.test_decorators.test_win32 ... ok
IPython.testing.tests.test_decorators.test_osx ... ok
Doctest: IPython.testing.tests.test_decorators.call_doctest_bad ... ok
Doctest: IPython.testing.tests.test_decorators.doctest_bad ... ok
Doctest: IPython.testing.tests.test_decorators.foo ... ok
Doctest: IPython.testing.tests.test_decorators.foo.__init__ ... ok
Doctest: IPython.testing.tests.test_decorators.foo.bar ... ok
Doctest: IPython.testing.tests.test_decorators.foo.baz ... ok
IPython.testing.tests.test_tools.test_full_path_posix ... ok
IPython.testing.tests.test_tools.test_full_path_win32 ... SKIP: Skipping test: test_full_path_win32. This test only runs under Windows

----------------------------------------------------------------------
Ran 35 tests 

OK (SKIP=2)
>print('hello')
>print('hello')
>print(1)
[?1034h---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)

     61         reload(sys.modules[modname])
     62     else:
---> 63         __import__(modname)
     64         
     65 

ImportError: No module named ipy_user_conf
WARNING: Loading of ipy_user_conf failed.

Doctest: IPython.deep_reload ... ok
Doctest: IPython.excolors.exception_colors ... ok
Doctest: IPython.genutils.EvalDict ... ok
Doctest: IPython.genutils.SystemExec ... ok
Doctest: IPython.genutils.qw ... ok
Doctest: IPython.genutils.read_dict ... ok
Doctest: IPython.iplib.InteractiveShell.cache_main_mod ... ok
Doctest: IPython.iplib.InteractiveShell.clear_main_mod_cache ... ok
Doctest: IPython.iplib.InteractiveShell.complete ... ok
Doctest: IPython.ipstruct.Struct ... ok
Doctest: IPython.ipstruct.Struct.__contains__ ... ok
Doctest: IPython.Magic.Magic.magic_alias ... ok
Doctest: IPython.Magic.Magic.magic_autocall ... ok
Doctest: IPython.Magic.Magic.magic_edit ... ok
Doctest: IPython.Magic.Magic.magic_macro ... ok
Doctest: IPython.Magic.Magic.magic_prun ... ok
Doctest: IPython.Magic.Magic.magic_reset ... ok
Doctest: IPython.Magic.Magic.magic_run ... ok
Doctest: IPython.Magic.Magic.magic_sc ... ok
Doctest: IPython.Magic.Magic.magic_time ... ok
Doctest: IPython.Magic.Magic.magic_timeit ... ok
Doctest: IPython.Magic.Magic.magic_timeit ... ok
Doctest: IPython.Magic.Magic.magic_timeit ... ok
Doctest: IPython.Magic.Magic.magic_who ... ok
Doctest: IPython.strdispatch.StrDispatch ... ok

----------------------------------------------------------------------
Ran 25 tests 

OK
>print(x)
[?1034h---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)

     61         reload(sys.modules[modname])
     62     else:
---> 63         __import__(modname)
     64         
     65 

ImportError: No module named ipy_user_conf
WARNING: Loading of ipy_user_conf failed.


----------------------------------------------------------------------
Ran 0 tests 

OK
[?1034h---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)

     61         reload(sys.modules[modname])
     62     else:
---> 63         __import__(modname)
     64         
     65 

ImportError: No module named ipy_user_conf
WARNING: Loading of ipy_user_conf failed.

Doctest: IPython.Extensions.astyle.Style.__init__ ... ok
Doctest: IPython.Extensions.clearcmd.clear_f ... ok
Doctest: IPython.Extensions.ipipe ... ok
Doctest: IPython.Extensions.ipipe.ialias ... ok
Doctest: IPython.Extensions.ipipe.icap ... ok
Doctest: IPython.Extensions.ipipe.icap ... ok
Doctest: IPython.Extensions.ipipe.ienum ... ok
Doctest: IPython.Extensions.ipipe.ienv ... ok
Doctest: IPython.Extensions.ipipe.ieval ... ok
Doctest: IPython.Extensions.ipipe.ifilter ... ok
Doctest: IPython.Extensions.ipipe.iglob ... ok
Doctest: IPython.Extensions.ipipe.ihist ... ok
Doctest: IPython.Extensions.ipipe.ils ... ok
Doctest: IPython.Extensions.ipipe.ipwd ... ok
Doctest: IPython.Extensions.ipipe.isort ... ok
Doctest: IPython.Extensions.ipipe.iwalk ... ok
Doctest: IPython.Extensions.ipipe.ix ... ok

----------------------------------------------------------------------
Ran 17 tests 

OK
[?1034h---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)

     61         reload(sys.modules[modname])
     62     else:
---> 63         __import__(modname)
     64         
     65 

ImportError: No module named ipy_user_conf
WARNING: Loading of ipy_user_conf failed.


----------------------------------------------------------------------
Ran 0 tests 

OK
*****************************************************************************
IPython test group: tests
*****************************************************************************
IPython test group: frontend
*****************************************************************************
IPython test group: tools
*****************************************************************************
IPython test group: testing
*****************************************************************************
IPython test group: modules
*****************************************************************************
IPython test group: UserConfig
*****************************************************************************
IPython test group: Extensions
*****************************************************************************
IPython test group: config

*****************************************************************************
Ran 8 test 

ERROR - 1 out of 8 test groups failed.
----------------------------------------
Runner failed: tests
You may wish to rerun this one individually, with:
iptest -v IPython.tests

